#!/bin/sh
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
const [maj, min, pat] = pkg.version.split('.').map(Number);
pkg.version = maj + '.' + min + '.' + (pat + 1);
fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
process.stdout.write('version bumped to ' + pkg.version + '\n');
"
git add package.json
